#!/bin/bash

CFG_FILE=".makefile_updater.config"


if [ "$1" == "reset" ]
then
	rm "$CFG_FILE"
fi

if test -f "$CFG_FILE"
then
	echo "Config found"
	source "$CFG_FILE"
else
	touch "$CFG_FILE"
	while :
	do
		read -p 'Are we in the Makefile directory ? [y=yes/n=no] : ' ANSWER
		if [[ "$ANSWER" == "y" || "$ANSWER" == "n" ]]
		then
			if [ "$ANSWER" == "n" ]
			then
				echo 'Please put this script in your Makefile  directory :)'
				exit 0
			fi
			break
		fi
		echo 'Wrong INPUT. please write y or n'
	done

	while :
	do
		read -p 'Do you have a source directory with .c files ? [y=yes/n=no] : ' ANSWER
		if [[ "$ANSWER" == "y" || "$ANSWER" == "n" ]]
		then
			if [ "$ANSWER" == "y" ]
			then
				read -p 'Please write the name of the directory : ' SOURCES
				SOURCES="${SOURCES}/"
			else
				SOURCES=""
			fi
			break
		fi
		echo 'Wrong INPUT. please write y or n'
	done
	read -p 'Last question. what is the name of the SOURCES in your makefile ? : ' SOURCES_NAME
	echo "SOURCES=${SOURCES}" >> "$CFG_FILE"
	echo "SOURCES_NAME=${SOURCES_NAME}" >> "$CFG_FILE"
fi

cd ..
NEW_SOURCES=$(ls -m $SOURCES*.c | tr -d ',')

NEWLINE="${SOURCES_NAME} = ${NEW_SOURCES}"

while IFS= read -r line
do
  if [[ $line == *"$SOURCES_NAME"* ]]
  then
    echo $NEWLINE
  	sed -i "" "s|$line|$NEWLINE|" "Makefile"
  	if [ "$?" != "0" ]
  	then
  		echo "Error with sed, sorry, you're probably on an OSX. It sucks."
  		exit 0
  	fi
  	break
  fi
done < "Makefile"

echo "Sources updated."
